### ISSUE TITLE
Fehler in Verbindung mit VIPS

### ISSUE THREAD

**Issue by Davka** [virtUOS/courseware#126]
Request-URL:
https://.../plugins.php/vipsplugin/sheets/get_character_picker_ajax?cid=...
Response:
{"status": 500, "message": "Das Plugin verfügt nicht über die gewünschte Operation"}
`[29-May-2017 13:48:31 Europe/Berlin] Exception: Das Plugin verf<FC>gt nicht <FC>ber die gew<FC>nschte Operation in /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php:367
Stack trace:
#0 /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php(330): AbstractStudIPLegacyPlugin->route('sheets/get_char...')
#1 /var/www/studip/public/plugins.php(56): AbstractStudIPLegacyPlugin->perform('sheets/get_char...')
#2 {main}
`

**Comment by Davka** [comment]
Der Fehler bzw. die Warning taucht immer noch auf:

[18-Oct-2017 15:00:01 Europe/Berlin] Exception: Das Plugin verf�gt nicht �ber die gew�nschte Operation in /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php:367
Stack trace:
#0 /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php(330): AbstractStudIPLegacyPlugin->route('sheets/get_char...')
#1 /var/www/studip/public/plugins.php(56): AbstractStudIPLegacyPlugin->perform('sheets/get_char...')
#2 {main}
[18-Oct-2017 15:00:02 Europe/Berlin] Exception: Das Plugin verf�gt nicht �ber die gew�nschte Operation in /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php:367
Stack trace:
#0 /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php(330): AbstractStudIPLegacyPlugin->route('sheets/get_char...')
#1 /var/www/studip/public/plugins.php(56): AbstractStudIPLegacyPlugin->perform('sheets/get_char...')
#2 {main}
[18-Oct-2017 15:00:02 Europe/Berlin] Exception: Das Plugin verf�gt nicht �ber die gew�nschte Operation in /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php:367
Stack trace:
#0 /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php(330): AbstractStudIPLegacyPlugin->route('sheets/get_char...')
#1 /var/www/studip/public/plugins.php(56): AbstractStudIPLegacyPlugin->perform('sheets/get_char...')
#2 {main}
[18-Oct-2017 15:00:03 Europe/Berlin] Exception: Das Plugin verf�gt nicht �ber die gew�nschte Operation in /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php:367
Stack trace:
#0 /var/www/studip/lib/plugins/core/AbstractStudIPLegacyPlugin.class.php(330): AbstractStudIPLegacyPlugin->route('sheets/get_char...')
#1 /var/www/studip/public/plugins.php(56): AbstractStudIPLegacyPlugin->perform('sheets/get_char...')
#2 {main}
[18-Oct-2017 15:00:04 Europe/Berlin] Excepti
