### ISSUE TITLE
Fehler beim erstellen eines Block innerhalb eines Kapitels (Version 2.1.4)

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#135]
2017/09/27 15:44:24 [error] 11590#0: *602 FastCGI sent in stderr: "PHP message: Error: Call to a member function isEditable() on null in /var/www/studip_3.5/public/plugins_packages/virtUOS/Courseware/blocks/Section/Section.php:119
Stack trace:
#0 [internal function]: Mooc\UI\Section\Section->add_content_block_handler(Array)
#1 /var/www/studip_3.5/public/plugins_packages/virtUOS/Courseware/models/mooc/ui/Block.php(265): call_user_func_array(Array, Array)
#2 /var/www/studip_3.5/public/plugins_packages/virtUOS/Courseware/controllers/blocks.php(206): Mooc\UI\Block->handle('add_content_blo...', Array)
#3 /var/www/studip_3.5/public/plugins_packages/virtUOS/Courseware/controllers/blocks.php(66): BlocksController->callBlockHandler(Object(Mooc\UI\Section\Section), 'add_content_blo...', Array)
#4 /var/www/studip_3.5/vendor/trails/trails.php(557): BlocksController->post('20')
#5 /var/www/studip_3.5/app/controllers/studip_controller.php(123): Trails_Controller->perform('20')
#6 /var/www/studip_3.5/vendor/trails/trails.php(154): StudipController->perform('20')
#7 /var/www/studip_3.5/" while reading response header from upstream, client: 134.106.68.93, server: nimuelle.uni-oldenburg.de, request: "POST /35/plugins.php/courseware/blocks/20 HTTP/1.1", upstream:

**Comment by nimuelle** [comment]
Nach einem Reload sind die gewünschten Blöcke dann da....
