### ISSUE TITLE
Error: Class 'ForumEntry' not found

### ISSUE THREAD

**Issue by tleilax** [virtUOS/courseware#199]
Das passiert scheinbar beim Importieren von exportierten Inhalten einer anderen VA:

```
2020/04/01 17:24:47 [error] 4710#4710: *76036340 FastCGI sent in stderr: "PHP message: Error: Class 'ForumEntry' not found in /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/blocks/ForumBlock/ForumBlock.php:95
Stack trace:
#0 /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/blocks/ForumBlock/ForumBlock.php(216): Mooc\UI\ForumBlock\ForumBlock->connectToArea('523cec768249609...')
#1 /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(295): Mooc\UI\ForumBlock\ForumBlock->importProperties(Array)
#2 /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(204): Mooc\Import\XmlImport->processBlockNode(Object(DOMElement), Object(Mooc\UI\Section\Section), Array)
#3 /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(169): Mooc\Import\XmlImport->processSectionNode(Object(DOMElement), Object(Mooc\DB\Block), Array)
#4 /var/www/studip-4.3/public/plugins_packages/virtUOS/Courseware/import/XmlImport.php(134): Mooc\Import\XmlImport->processSubChapterNode(Object(DOMElement)," while reading response header from upstream, client: 37.138.99.15, server: elearning.uni-oldenburg.de, request: "POST /plugins.php/courseware/block_manager/import_complete_archive HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "elearning.uni-oldenburg.de", referrer: "https://elearning.uni-oldenburg.de/plugins.php/courseware/block_manager/index?cid=9c3bae893e1b182f36e8bc649c3b1143"
```

**Comment by rlucke** [comment]
fixed with b3e9c5ec26b83af6564c4a96db9e8f426e285371
