### ISSUE TITLE
Fehler beim Kopieren von Coursewareinhalten in 4.6

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#240]
```
2021/03/18 13:15:56 [error] 3959#3959: *6175079 FastCGI sent in stderr: "PHP message: Error: Call to undefined method FileManager::copyFileRef() in /var/www/studip-4.6/public/plugins_packages/virtUOS/Courseware/controllers/block_manager.php:564
Stack trace:

#0 /var/www/studip-4.6/vendor/trails/trails.php(557): BlockManagerController->store_changes_vue_action()

#1 /var/www/studip-4.6/app/controllers/studip_controller.php(110): Trails_Controller->perform('store_changes_v...')

#2 /var/www/studip-4.6/vendor/trails/trails.php(154): StudipController->perform('store_changes_v...')

#3 /var/www/studip-4.6/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('block_manager/s...')

#4 /var/www/studip-4.6/public/plugins_packages/virtUOS/Courseware/Courseware.php(287): Trails_Dispatcher->dispatch('block_manager/s...')

#5 /var/www/studip-4.6/public/plugins.php(54): Courseware->perform('block_manager/s...')

#6 {main}" while reading response header from upstream, client: 134.106.68.93, server: elearning.uni-oldenburg.de, request: "POST /plugins.php/courseware/block_manager/store_changes_vue HTTP/2.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "elearning.uni-oldenburg.de", referrer: "https://elearning.uni-oldenburg.de/plugins.php/courseware/block_manager/index?cid=b6477dd15d9fbb674512f897ec4f8a51"
```
Immer dann, wenn Dateien eingebunden sind, geht es kaput....

Da müsstet ihr nochmal ran.....

**Comment by nimuelle** [comment]
Es sieht wohl so aus, als ob der gesamte Import-Export in der 4.6 nicht mehr funktioniert

Pluginversion 4.8.4
