### ISSUE TITLE
PDF-Export schlägt fehl

### ISSUE THREAD

**Issue by Davka** [virtUOS/courseware#281]
```
2021/11/17 11:47:12 [error] 4072333#4072333: *7713987 FastCGI sent in stderr: "PHP message: Mooc\UI\Errors\BadRequest: No such view. in /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/models/mooc/ui/Block.php:232
Stack trace:
#0 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/models/mooc/ui/Block.php(701): Mooc\UI\Block->render()
#1 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/controllers/pdf_export.php(149): Mooc\UI\Block->exportBlockIntoPdf()
#2 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/controllers/pdf_export.php(97): PdfExportController->writeBlock()
#3 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/controllers/pdf_export.php(58): PdfExportController->writeItem()
#4 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/controllers/pdf_export.php(65): PdfExportController->visitItem()
#5 /opt/studip/studip_46/public/plugins_packages/virtUOS/Courseware/controllers/pdf_export.php(65): PdfExportController->visitItem()
#6 /opt/studip/studip_46/public/plugins_packages/virtUO" while reading response header from upstream, client: 172.25.43.69, server: studip.uni-vechta.de, request: "GET /plugins.php/courseware/pdf_export?cid=cid
````

**Comment by rlucke** [comment]
fix in portfolio46 Branch
